export const main: string
export const top: string
export const channel: string
export const title: string
export const time: string
export const description: string
export const bottom: string
export const activeGoing: string
export const activeLike: string
