export const main: string
export const bottom_comment: string
export const comment: string
export const send: string
export const input: string
export const bottom_normal: string
export const purple: string
export const bottom: string
export const likes_active: string
export const join: string
export const join_active: string
export const toast: string
