export const container: string
export const gallery: string
export const description: string
export const expend_cover: string
export const expend_button: string
export const when: string
export const where: string
export const when_title: string
export const where_title: string
export const when_detail: string
export const date: string
export const time: string
export const where_location: string
export const where_detail: string
