export const main: string
export const bg: string
export const smallTitle: string
export const bigTitle: string
export const logoContainer: string
export const logo: string
export const input: string
export const user: string
export const password: string
export const userInput: string
export const passwordInput: string
export const bottom: string
export const lang: string
